### PR TITLE
support current ST_ASMVT parameters

### PR DESCRIPTION
**Pull request by smellman**
@sk1p comment me in https://github.com/openmaptiles/postgis/pull/10#issuecomment-464446991

I just make [PR for postgis docker image](https://github.com/openmaptiles/postgis/pull/11) and I update postserve to support current ST_ASMVT.
I will test with planet (importing time over 32hours).

### CODE REVIEW

**Comment by nyurik** [comment]
@smellman I actually had to do a full rewrite of this tool, see #11 -- it is far cleaner now,
without any locally done modifications.  I won't merge it until I merge the proper SQL generation
into the openmaptiles repo.

**Comment by smellman** [comment]
I will close this PR and I will make new PR with support buffer-size property. Also, I have other problem so I research it now.

**Comment by nyurik** [comment]
@smellman what do you mean by the buffer-size property?  The buffer sizes are generated as part of the [SQL generation](https://github.com/openmaptiles/openmaptiles-tools/pull/34/files#diff-547b229652e18895a3c7488e08d66ac5R93) -- because each layer has its own settings for the buffer sizes.

**Comment by smellman** [comment]
Yes, I just upload my [WIP branch](https://github.com/smellman/postserve/tree/dev-postgis-2.5.1-buffer-size-support).
I found 0/0/0 problem when I test this branch.

**Comment by nyurik** [comment]
@smellman could you paste your generated query to a gist? (as printed by your postserve when it starts) .  This way it will be easier to compare just the SQL, and how it executes.

**Comment by nyurik** [comment]
@smellman   postserve has been merged to https://github.com/openmaptiles/openmaptiles-tools#test-tiles -- we should close this repo

**Pull request closed without merging**
